import {
  ITreeItem,
  KinshipEnum,
} from '../../components/genealogy-tree/interfaces';

export const treeItems: ITreeItem = {
  id: '1',
  name: 'Я',
  alive: true,
  avatar: 'https://sun9-5.userapi.com/impf/c834401/v834401781/39849/D3UI7yjK60U.jpg?size=599x900&quality=96&sign=3cb8920cd8f60cbb922f776f13edf1c9&type=album',
  birthday: new Date('1991.03.25'),
  kinship: KinshipEnum.YOU,
  isVisible: true,
  children: [
    {
      id: '2',
      name: 'Седлецкая Мария',
      alive: true,
      avatar: '',
      birthday: new Date('1990.01.23'),
      kinship: KinshipEnum.WIFE,
      children: [],
      isVisible: true,
    },
    // {
    //   id: '3',
    //   name: 'Могилевцева Арина',
    //   alive: true,
    //   avatar: '',
    //   birthday: new Date('2019.09.03'),
    //   kinship: KinshipEnum.DAUGHTER,
    //   children: [],
    //   isVisible: true,
    // },
    // {
    //   id: '4',
    //   name: 'Могилевцева Ксения',
    //   alive: true,
    //   avatar: '',
    //   birthday: new Date('2014.04.02'),
    //   kinship: KinshipEnum.DAUGHTER,
    //   children: [],
    //   isVisible: true,
    // },
    // {
    //   id: '5',
    //   name: 'Могилевцева Алена',
    //   alive: true,
    //   avatar: '',
    //   birthday: new Date('1992.05.18'),
    //   kinship: KinshipEnum.SISTER,
    //   children: [],
    //   isVisible: true,
    // },
    // {
    //   id: '6',
    //   name: 'Могилевцев Александр',
    //   alive: true,
    //   avatar: '',
    //   birthday: new Date('1965.06.30'),
    //   kinship: KinshipEnum.FATHER,
    //   children: [],
    //   isVisible: true,
    // },
    // {
    //   id: '7',
    //   name: 'Могилевцева Ирина',
    //   alive: true,
    //   avatar: '',
    //   birthday: new Date('1971.01.09'),
    //   kinship: KinshipEnum.MOTHER,
    //   isVisible: true,
    //   children: [
    //     {
    //       id: '8',
    //       name: 'Вопилова Наталья',
    //       alive: true,
    //       avatar: '',
    //       birthday: new Date('1971.01.09'),
    //       kinship: KinshipEnum.SISTER,
    //       isVisible: true,
    //       children: [
    //         {
    //           id: '9',
    //           name: 'Вопилов Андрей',
    //           alive: true,
    //           avatar: '',
    //           birthday: new Date('1971.01.09'),
    //           kinship: KinshipEnum.SON,
    //           children: [],
    //           isVisible: true,
    //         },
    //       ],
    //     },
    //     {
    //       id: '10',
    //       name: 'Беда Николай',
    //       alive: true,
    //       avatar: '',
    //       birthday: new Date('1944.11.01'),
    //       kinship: KinshipEnum.FATHER,
    //       children: [],
    //       isVisible: true,
    //     },
    //     {
    //       id: '10',
    //       name: 'Беда Валентина',
    //       alive: true,
    //       avatar: '',
    //       birthday: new Date('1949.08.16'),
    //       kinship: KinshipEnum.MOTHER,
    //       children: [],
    //       isVisible: true,
    //     },
    //   ],
    // },
  ],
};
