import { ITreeItem, KinshipEnum } from './interfaces';

export const treeItems: ITreeItem = {
  id: '1',
  name: 'Я',
  alive: true,
  avatar: '',
  birthday: new Date('25-03-1991'),
  kinship: KinshipEnum.YOU,
  relations: [
    {
      id: '2',
      name: 'Седлецкая Мария',
      alive: true,
      avatar: '',
      birthday: new Date('23-01-1990'),
      kinship: KinshipEnum.WIFE,
      relations: [],
    },
    {
      id: '3',
      name: 'Могилевцева Арина',
      alive: true,
      avatar: '',
      birthday: new Date('03-09-2019'),
      kinship: KinshipEnum.DAUGHTER,
      relations: [],
    },
    {
      id: '4',
      name: 'Могилевцева Ксения',
      alive: true,
      avatar: '',
      birthday: new Date('02-04-2014'),
      kinship: KinshipEnum.DAUGHTER,
      relations: [],
    },
    {
      id: '5',
      name: 'Могилевцев Алена',
      alive: true,
      avatar: '',
      birthday: new Date('18-05-1992'),
      kinship: KinshipEnum.SISTER,
      relations: [],
    },
    {
      id: '6',
      name: 'Могилевцев Александр',
      alive: true,
      avatar: '',
      birthday: new Date('30-06-1965'),
      kinship: KinshipEnum.FATHER,
      relations: [],
    },
    {
      id: '7',
      name: 'Могилевцева Ирина',
      alive: true,
      avatar: '',
      birthday: new Date('09-01-1971'),
      kinship: KinshipEnum.MOTHER,
      relations: [
        {
          id: '8',
          name: 'Вопилова Наталья',
          alive: true,
          avatar: '',
          birthday: new Date('09-01-1971'),
          kinship: KinshipEnum.SISTER,
          relations: [
            {
              id: '9',
              name: 'Вопилов Андрей',
              alive: true,
              avatar: '',
              birthday: new Date('09-01-1971'),
              kinship: KinshipEnum.SON,
              relations: [],
            },
          ],
        },
        {
          id: '10',
          name: 'Беда Николай',
          alive: true,
          avatar: '',
          birthday: new Date('01-11-1944'),
          kinship: KinshipEnum.FATHER,
          relations: [],
        },
        {
          id: '10',
          name: 'Беда Валентина',
          alive: true,
          avatar: '',
          birthday: new Date('16-08-1949'),
          kinship: KinshipEnum.MOTHER,
          relations: [],
        },
      ],
    },
  ],
};
